name: lint
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.1.0
        with:
          node-version: 'lts/*'
      - run: npm ci
      - run: npm run lint
